### PR TITLE
Fix configuration directory creation.

### PR DESCRIPTION
**Pull request by chaoren**
- Simplify creath_path
- More sane permissions
- Create entire path of configuration directory

### CODE REVIEW

**Comment by tambry** [comment]
@chaoren It seems that the "common" submodule is no longer used in the main repository. @Nekotekina reverted some DH's changes to fix master. "Common" remains part of the main repository for now.

**Comment by chaoren** [comment]
You mean Utilities/? I'll cherry-pick this over.

**Comment by tambry** [comment]
@chaoren Yes.

**Comment by chaoren** [comment]
Merged. https://github.com/RPCS3/rpcs3/commit/4e08d35661ffc5d93defa3190f57dac4bff68f4a

**Pull request closed without merging**
